COMMODITIES = {
    "LST": "Limestone",
    "MAR": "Marble",
    "AU": "Gold",
    "PGM": "Platinum Group Metals",
    "Nf": "Nuclear Fuel Minerals",
    "NFM": "Nuclear Fuel Minerals",
    "Nnf": "Non-Nuclear Fuel Minerals",
    "NNF": "Non-Nuclear Fuel Minerals",
    "PM": "Precious Metals",
    "BM": "Base Metals",
    "BRM": "Base and Rare Metals",
    "PM": "Precious Metals",
    "SPS": "Semi-Precious Stones",
    "IM": "Industrial Minerals",
    "DS": "Dimension Stone",
    "PS": "Precious Stones",
}
